### ISSUE TITLE
[close-duplicate-tabs] active tab should be considered for duplicate check

### ISSUE THREAD

**Issue by allanwind** [igorlogius/igorlogius#14]
**Steps to Reproduce**

1. Open tab t1
2. Open tab t2 (duplicate of t1)
3. Open tab t3 (non-duplicate)

**Expected result**
 
1 duplicate regardless of which tab is active. If tab t1 is active then tab t2 should be deleted, and if tab t2 is active then tab t1 should be deleted.

**Actual result**

If tab t1 or t3 are active then 0 duplicates are reported and none are deleted.

**Comment by igorlogius** [comment]
I'll admit that the behaviour of the addon is unexpected with the `ignore selected tabs` option enabled. I know i had some trouble getting this function to work as expected and at one point settled for the behaviour you noticed, which is not perfect. I'll leave this issue open ... and when i have a good day see what i can do to improve/fix this. Sadly its not something to easy to just add, as far as i remember.

**Comment by allanwind** [comment]
I believe in you :-)

**Comment by igorlogius** [comment]
`1.0.22`

- active tab is considered for badge icon calculation
- active tab is never closed / excluded from removal  
- if the option to keep older tabs is enabled, and a newer duplicate is the active tab, this will keep both the oldest duplicate and the active duplicate open. => Might seem a bit unintuitive but just closing the active tab or switching to the older one ... seems like a worse idea/option.

**Comment by allanwind** [comment]
You revised the comment but "if the option to keep older tabs is enabled, and a newer duplicate is the active tab" then close the older tab instead of leaving both open (imho).
