### ISSUE TITLE
bug report template typo

### ISSUE THREAD

**Issue by allanwind** [igorlogius/igorlogius#15]
**Actual result**
Short description of what actually happend.

"happend" should "happened"

**Comment by allanwind** [comment]
It's not clear to me what you want from the title with [<project name>].  Does [] mean it's optional?  Or do you want those square brackets?  `<project name>` is a variable, I guess, but why is that `<>`?

**Comment by igorlogius** [comment]
Thanks. I'll fix that. 

The square brackets are intended as a seperator. 

The angle brackets `<>` indicate a variable that should be replace completely by user content. 

Dont worry too much about it.   :-)

**Comment by igorlogius** [comment]
fefc04b
