### ISSUE TITLE
[close-duplicate-tabs] It's confusing that Issues tab is disabled

### ISSUE THREAD

**Issue by allanwind** [igorlogius/igorlogius#16]
I was really confused when trying to find the close-duplicate-tabs Issue tab to file a bug report.  It's your projects, so you can do whatever you want of course, but you may want to add something to each project's readme to point to this repo as it's an unusual setup.  I did see the home page pointing to this repo, and I thought initially it's a minor defect.

**Comment by igorlogius** [comment]
I was already planing on adding this info at the top of each repo README but just did not yet get around to it. I'll get there give me a little time please.
