### ISSUE TITLE
[close-duplicate-tabs] ignore fragment

### ISSUE THREAD

**Issue by allanwind** [igorlogius/igorlogius#17]
I forgot what site I was on, and how I ended up with both url.  It might have been duplicating a url, then clicking a link, and then clicking the back button and now ending up on the url with the empty fragment (buggy SPA thingy).

**Steps to Reproduce**

1. Open tab t1 https://www.mozilla.org/en-US/
2. Open tab  t2 https://www.mozilla.org/en-US/#

**Expected result**
1 duplicate. 

**Actual result**
No duplicates.

**Other additional information**
If the fragment isn't empty, though, it should still retain the current behavior and treat them as non-duplicate urls.  I have only seen this once since you created this add-on so it's super minor.

**Comment by igorlogius** [comment]
> Expected result 1 duplicate.

I am not confident other users would agree with you

**Comment by allanwind** [comment]
"I am not confident other users would agree" is not a valid argument (FUD) as you only have 1 data point (me).  If you use the add-on and disagree then it's totally fair if you outright reject the issue.  I appreciate your style of being open to input :-)

The best authoritative argument might be https://developer.mozilla.org/en-US/docs/Web/API/URL/hash which says:

> The hash property of the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface is a string containing a '#' followed by the fragment identifier of the URL. [...]  If the URL does not have a fragment identifier, this property contains an empty string — ""

The two original url would have the same hash property value (""), and the example you gave are all distinct ("", "#", and "ABC#").  This is issue is a special case for the empty fragment only, and I would literally just do a regex replace "#$" -> "" of the text url.

I am good with whatever you decide.

**Comment by igorlogius** [comment]
`1.0.20` adds a simple for the most common case where just an empty fragment identifier is trailing behind the rest of the url. That should be good enough for now.
