### ISSUE TITLE
[Bookmark Tabs] - prompt for save folder name  & set a custom base folder

### ISSUE THREAD

**Issue by Vitaminol** [igorlogius/igorlogius#18]
Hi, igorlogius,
Thankyou for your wonderful add-on Bookmark Tabs.

**Is your feature request related to a problem? Please describe.**
Difficult to find tabs I'm looking for in a stack of folders named by dates of creation.

**Describe the solution you'd like**
While saving selected tabs I'd like to have a pop-up prompting for a custom folder name input. By default, it can be filled out with the current date and time.

**Describe alternatives you've considered**
Besides, it would be great to give me a choice where to attach the folder. Now it is firmly fixed to Other bookmarks.

Again, thank you for your work!

**Comment by igorlogius** [comment]
Thanks for the feedback. 
Both your requests are reasonable and i see the usecases.

It's just a difficult when i think about how to best implement these in a way that doesnt suck, since my options on how this could be done is limited. (for example i cant really open a popup inside the browser window ... the  only options i have are to open a new tab or new small window for userinput. Both options don't immediately seem like a very nice, at first glance.

**Comment by igorlogius** [comment]
But maybe it'd be simpler if you just switched to this addon 

https://addons.mozilla.org/en-US/firefox/addon/save-all-my-tabs/

At a glance it seems like it might already have all the functions.

**Comment by igorlogius** [comment]
Well, ... the github page for 'save-all-my-tabs' doenst seem to be very active ... and there are a few open issues. ... ok, so if you dont get a respsone in a timely manner (couple of weeks) ... you can let me know and i might take a crack at this instead.

**Comment by Vitaminol** [comment]
Dear sir!

Thank you for your prompt reply. 

Your add-on has huge advantages over the other you've mentioned: 
1. My tabs are grouped with Panorama View add-on, and I need to save only tabs in a group. The other tab saves all, including the hidden ones.
2. Your add-on cares for structure, it creates a folder. The other one just piles the tabs into the folder where other tabs might already exist.

All-in-all I will stay with Bookmark Tabs. Actually it's no big deal to rename a folder.

Thank's again.
Regards

Вы писали 2024.05.10, 22:08:02:

> Well, ... the github page for 'save-all-my-tabs' doenst seem to be very active ... and there are a few open issues. ... ok, so if you dont get a respsone in a timely manner (couple of weeks) ... you can let me know and i might take a crack at this instead.

**Comment by igorlogius** [comment]
Mmh, thats some insightful feedback about your workflow ... let me digest this a little

**Comment by Vitaminol** [comment]
Oh, and I forgot another thing - it would be great to add an option either to immediately close the saved tabs, or to live them open. Now they are always open.

Вы писали 2024.05.11, 15:32:02:

> Mmh, thats some insightful feedback about your workflow ... let me digest this a little

**Comment by igorlogius** [comment]
@Vitaminol checkout the new version `1.6.17`


[demo-2024-05-11_18.39.11.webm](https://github.com/igorlogius/igorlogius/assets/67047467/ba725777-c084-4edd-80e3-333bbebd62e1)


As you can see this one allows to add a custom postfix to the folder and you can also quickly change the base folder for the saves. 

The original function is also still covered by the shortcut, which i hope is enough to make other users not complain about changing the function of the toolbar button.

**Comment by igorlogius** [comment]
> Oh, and I forgot another thing - it would be great to add an option either to immediately close the saved tabs, or to live them open. Now they are always open.

Eh, sure, why not.

**Comment by igorlogius** [comment]
@Vitaminol check `1.6.18` 

![2024-05-11_19-22](https://github.com/igorlogius/igorlogius/assets/67047467/58e397e5-c117-4450-91d0-857a876a9ffb)
