### ISSUE TITLE
[new add-on] tab notes

### ISSUE THREAD

**Issue by atomGit** [igorlogius/igorlogius#2]
hello again!

i use an old add-on called Mark-It which simply changes the new tab page in Firefox to a markdown/html notepad - it is **amazingly handy**, however it disappeared from AMO and though there are several other add-ons that claim similar functionality, none of them are as simple or work as well (and i looked at or tried every single one i could find)

i would like to propose the development of a replacement for Mark-It that does nothing more than provide for an MD/HTML new tab page

Mark-It, as i recall, used a 3rd party lib for MD syntax, however i suspect that's not strictly necessary - i think the conversion to HTML could be done via RegEx and JS - i think support for only the most basic MD is necessary (headings, lists, bold, italic, code (in-line and block) - check-boxes might also be worthwhile if their state can be remembered across sessions, but even that isn't super important to me

i can send you the Mark-It xpi if wish

**Comment by igorlogius** [comment]
Hi. Hope you are doing well. 

For me to consider this ... i first would like to understand which functionalitys of `Mark-it` isn't present in all the other addons, since form your description this https://addons.mozilla.org/en-US/firefox/addon/markdown-new-tab/ at first glance matchs `replaces newtab page with a editable markdown page`.

Yes, please also share the XPI with me. It might make it easier for me to understand what is different about Mark-It.

**Comment by atomGit** [comment]
Markdown New Tab is simply [badly broken](https://github.com/plibither8/markdown-new-tab/issues) and the developer is not responsive

there are other add-ons which support MD, but (somehow) not HTML - most are quite old as i recall - others are bloated with unnecessary deps (google fonts for ex.), or unnecessary "bling", or are restricted in some way - one of them uses a convoluted method of having to create containers for text and editing the content

there are literally none that i could find that are as simple and work as well as Mark-It and i've looked over and over (and over) again for probably more than a year for a suitable replacement

Mark-It still works fine in the most recent FF version, with the minor caveat that it doesn't always load when the browser is first started (close the new tab to open another and it always loads fine) - other than that there are no bugs i'm aware of, though i think the css could use some minor tweaks

the end result with Mark-It is a whole-screen notepad which can be a waste of space, however give that it does HTML, it's easy to bust up into sections `<div>` with some custom css ... speaking of which, i suppose it might be nice to be able to inject the css from add-on settings rather than userContent.css, but that's a minor issue

[mark_it-1.2.1-fx.zip](https://github.com/igorlogius/igorlogius/files/14270028/mark_it-1.2.1-fx.zip)

**Comment by igorlogius** [comment]
Lets make a list (i like lists)

- existing addons have some bugs (mostly formating issues)
- missing plain HTML support in MD editor 
- not maintained 
- bloated/ have external deps
- restricted in some way (not sure exactly what this means)

I'll take a look at Mark-It and think about this a little and come back to you.

**Comment by atomGit** [comment]
ps: if you decide to not take this on, i will of course understand completely, but if you do, i think this would be a near-zero maintenance project since it's such a simple thing (to the end user)

**Comment by atomGit** [comment]
> restricted in some way (not sure exactly what this means)

no html support in at least one of them, but what i was really referring to is how it works or what it can't do - for example being restricted to a limited number of separate notes (instead of an unlimited, full-tab page (one big, single note)) - i think in another case the MD is only partially converted, so `# heading` for ex. displays as `<h1>`, but the hash char is still there

Markdown New Tab was the worst of them - it's just plain broken - certain settings are not saved and content is not restored on browser restart in some cases as i recall (maybe he's using the wrong API)

**Comment by atomGit** [comment]
if you want to add to your list, there are multiple extensions that support text, but not MD

**Comment by igorlogius** [comment]
> doesn't always load on browser start (when starting with a blank tab) (minor/moderate)

Could this be because the browser starts up with `about:home` instead of `about:newtab` ?

**Comment by atomGit** [comment]
home page is set to about:blank and new tab page is set to Mark-It

i just tried setting home to the extension URL but the geniuses at Moz decided to not allow it (it defaults to about:home)

**Comment by igorlogius** [comment]
Sorry, but i'll have to decline this request.
The work involved making the requested changes seem a bit more than i feel like i could/want to manage at the moment.

**Comment by atomGit** [comment]
i kan"t cee mi keebrd to r3ply 1'm kryng soo hard :cry: 

no problem and thanks for taking the time to have a look at it anyway - if you happen to know of a dev in need of project, feel free to pass it on
