### ISSUE TITLE
 Just some positive feedback and Praise.

### ISSUE THREAD

**Issue by Previll** [igorlogius/igorlogius#24]
I just noticed in your about page you are privacy focused, so asking for another method to donate was inappropriate of me. My apologies
### Description

Mate I don't have a feature suggestion I just wanted to tell you, you've got some of the most useful extensions i've ever seen and use every day. I don't have any bitcoin for a donation, but if you have a paypal or some other link I can use, I'd love to buy you a six pack of beers or something.

Great stuff man!

**Comment by igorlogius** [comment]
Thank you and don't worry about the donation thing.

You taking the time to share this feedback is much more valuable in my book.
Knowing people find the stuff i make useful is really motivating. 

So thank you again for writing and if you do have a suggestion in the future, feel free to open another issue.

[See you around and party on!](https://www.youtube.com/watch?v=N_yJFLvmjJY)
