### ISSUE TITLE
[Open in Temp Container] Exceptions list

### ISSUE THREAD

**Issue by anewuser** [igorlogius/igorlogius#25]
### Description

Hello. Could you add "Never open these URLs in temp containers" to the list of "operation modes"?

This is what I would like to achieve:

* Browse a site in a temp container
* Click on a link to `https://example.org/` 
* `[default container] https://example.org/` opens in a new tab.

**Comment by igorlogius** [comment]
... mmh, i am not sure if that function is really necessary, since opening a link outside of a container is still doable via the context menu. 

![2024-06-21_09-27](https://github.com/igorlogius/igorlogius/assets/67047467/2bb34c27-dd18-41f0-9991-e0b7949d4984)

**Comment by anewuser** [comment]
The thing is that I don't always know when a link leads to the sites I would add to this list. 

This redirection to the default container could also prevent us from opening those sites accidentally, for example:

* Browse in a temporary container
* Focus the address bar and enter a search query

Result: your search results open in the temporary container.

Expected result: a new tab would open with your search results in the default container, also preserving the temporary container and its tab history.

This can be achieved with the [Containerise](https://addons.mozilla.org/addon/containerise/) extension configured to `Keep old tabs`, but since this is my only use for it, I thought of sharing this idea with you.

**Comment by igorlogius** [comment]
yeah, maybe a list for url regex matches to exclude from always opening in a temp container could be useful ... i'll see what i can do. 

Might take me a little while since i am currently a bit sick ... but i'll try and get to it when i am better again.

**Comment by anewuser** [comment]
Sorry to hear that. I hope you get well soon!

**Comment by igorlogius** [comment]
The automatic temp container breakout list ("Exclusion Matches" might rename that ) is available in the experimental section in version `1.1.34`. Please note: The breakout list has the highest priority so it beats any other instruction. (like open xyz url in temp container)

Test it out and tell me if there is anything not working as you would expect.


[demo-2024-06-23_19.39.55_small.webm](https://github.com/igorlogius/igorlogius/assets/67047467/7079fa2d-6dad-43ed-a917-6ecb2a08d2da)

**Comment by anewuser** [comment]
The new rules are breaking pages with iframes.

* Add these rules:

```
    ^https:\/\/www.youtube.com\/*
    ^https:\/\/youtu.be\/*
```
    
 * Open a temporary container with https://opeforum.com/threads/worst-saw-videos-on-the-net.11582/

**Comment by igorlogius** [comment]
> All types of rules should ignore iframes.

should be fixed in `1.1.35`

**Comment by igorlogius** [comment]
Might need to take another look at the position of the tabs ...

**Comment by anewuser** [comment]
- [ ] The original tab is lost if you do this:


* Open some site in a temporary container
* Access https://www.youtube.com/ from the address bar



-----

- [ ] The "Special options" section is not expanding automatically when I go back to the options tab. 

If it's not possible to expand it automatically when the user has already created personal rules, maybe you could remove this toggle and just replace it with a large warning header.

-----

- [ ] Just a minor detail: the final slashes (`/`) in your placeholder example rules aren't escaped.

----

I also experience this while selecting rules on Windows. Is this a Firefox bug?

![bug](https://github.com/igorlogius/igorlogius/assets/6733770/584754ba-d028-4a78-b767-47596544c54d)

**Comment by igorlogius** [comment]
> 1. The original tab is lost if you do this:

well ... i can't distinguishe from where a navigation is triggered, so AFAIK, there is no solution for this at the moment. 

> 2. The "Special options" section is not expanding automatically when I go back to the options tab.

Doenst seem to be strictly necessary , but i'll think about it.

> 3. Just a minor detail: the final slashes (/) in your placeholder example rules aren't escaped.

Thanks, i'll fix the exmples.

> I also experience this while selecting rules on Windows. Is this a Firefox bug?

Not sure. At least i am not aware adding anything that might cause this. 
The UI is made up of standard form elements and nothing more.

**Comment by igorlogius** [comment]
> Some people apparently [pay to use more than three temporary containers](https://ghostbrowser.com/upgrade/).

That seems scam'ish.

> [Here's the bug report about the textarea glitch](https://bugzilla.mozilla.org/show_bug.cgi?id=1904286).

I'll keep an eye on that. Thanks.

**Comment by Gitoffthelawn** [comment]
@anewuser Thank you for thinking of me.

@igorlogius This looks promising.  Thank you.

I have a couple big upcoming deadlines, so I quickly skimmed all the above and saved the thread to look at more closely in the future.
