### ISSUE TITLE
[Bookmark Branch Porter]: html export seems to lose utf-8 encoding

### ISSUE THREAD

**Issue by denniz-j** [igorlogius/igorlogius#26]
### Steps to Reproduce

1. with Bookmark Branch Porter installed.
2. Got to a web page with a utf-8 title, like  https://addons.mozilla.org/en-US/firefox/addon/bookmark-branch-porter/
3. bookmark the page
4. go to "manage bookmarks", right-click on the above bookmark and choose "Bookmark Branch Porter > Export branch (HTML)"
5. go to the file location to which you exported the bookmark and examine the content of the exported html file.

### Expected Result

I expected the link text of the bookmark to be:

Bookmark Branch Porter – Get this Extension for 🦊 Firefox (en-US)

### Actual Result

Actual text was:
 
`Bookmark Branch Porter â Get this Extension for ð¦ Firefox (en-US)`

(I'm assuming the bug reporting system on github does not further mangle the text.)

### Additional Information

"Bookmark Branch Porter > Export branch (JSON)" works as expected, that is, it produces:

"title": "Bookmark Branch Porter – Get this Extension for 🦊 Firefox (en-US)",

And "Export Bookmarks as Text" works as expected, it produces:

Bookmark Branch Porter – Get this Extension for 🦊 Firefox (en-US) : https://addons.mozilla.org/en-US/firefox/addon/bookmark-branch-porter/

Debian 11 Bullseye
Name: Firefox
Version: 127.0
Build ID: 20240606181944
OS: Linux 5.10.0-29-amd64 #1 SMP Debian 5.10.216-1 (2024-05-03)

Thank you. I've just found your export addons, and I think they might turn out to be handy.

**Comment by igorlogius** [comment]
Thank you for the report!

It seems a codepoint to html entity conversion for the bookmark title was missing. 

Should be fixed in `1.4.18`

![2024-06-22_09-17](https://github.com/igorlogius/igorlogius/assets/67047467/7dafd0e2-e982-4a8f-af54-51cbb17325d4)
