### ISSUE TITLE
[new add-on] copy and format text

### ISSUE THREAD

**Issue by atomGit** [igorlogius/igorlogius#3]
[Format Link](https://github.com/hnakamur/FormatLink-Firefox) is a one-of-kind add-on for formatting copied content - it is extremely useful and it works very well, however it needs some polish and the developer hasn't been all that responsive to requests (i'm not knocking him - perhaps he just doesn't have the time)

this _powerful_ add-on can format text in many different ways, as well as leverage JS RegEx to do things like removing non-print chars, perform search-replace functions, like replacing `<br><br>` with `</p><p>` if working with HTML, converting content to BB code, markdown, etc., et., etc....

it can also copy and format page titles and URLs along with selected text which makes it super useful for news publishers

![format-link](https://github.com/igorlogius/igorlogius/assets/1817307/6ad87ff3-5f08-444e-aac5-3073ee918424)

there's several similar add-ons on AMO, but none that are as good or as featured 

there are key issues with the current version however...

* limited format options (9)
* inability to easily re-order format options
* lacks a dark theme
* no included guide/documentation

**Comment by igorlogius** [comment]
> needs some polish 

You know my addons are famously ugly and unpolished with the only exception of maybe  `copy-tabs`, but jokes aside, 

i could take a look at the addon. It seems to be pretty similar to my `copy link extras` only it works on text selections, which really isnt that different. 

BUT looking at https://github.com/hnakamur activity it seems at least he is alive Feb 2024 so maybe you should try contacting him again first. 

If he doesnt respond in the next 4-6 weeks, hit me up again and i'll think about creating a fork or maybe creating something of my own with the same functionality. 

Sounds fair?

**Comment by atomGit** [comment]
absolutely! 

however, the suggestion to add unlimited formatting options was brought up in [2022](https://github.com/hnakamur/FormatLink-Firefox/issues/51) and again in [2023](https://github.com/hnakamur/FormatLink-Firefox/issues/57) with no response from the dev

i opened another [2022](https://github.com/hnakamur/FormatLink-Firefox/issues/52) request to simply add basic format help info to the add-on page and again, nothing

that said, he has been helpful with support requests (format syntax)

if you want me to have another whack at it, let me know and i'll re-raise these issues

> You know my addons are famously ugly and unpolished. :-)

hehe :) if its a layout or css thing, i might be able to help, but the main issues are limited format options, absent help text and, to a somewhat lessor extent, inability to easily re-order items (i linked to code in one of the above linked issues that does drag-n-drop ordering in an effort to help the developer)

**Comment by igorlogius** [comment]
Just noticed that the addon allows to map all formats to a custom shortcut.

That might explain why the list of formats was not made to be dynamic, because addons are only allowed to have a limited number of shortcuts.

So here we have a priority question/issue. Is it more important to have a shortcut for every format or is it more important to have more formats but forgo having shortcuts for every format option? 

I assume you would say more formats are better, even if those aren't as convinienlty accessable.

**Comment by atomGit** [comment]
if it's possible to have unlimited formats, but a limited number of shortcuts, i would opt for that first as long as it's not too difficult

if that's not doable, then the shortcuts (for me) take priority over unlimited formats and if another, say, 6 formats were added (15 ttl), that'd be plenty in my case and probably for most others as well

that said, the way i use the ext. requires only one hotkey to open the pop-up and auto-apply the last used format (which is remembered), so i don't use any shortcuts for any specific format ... so far as i'm concerned, all but one shortcut option could be removed, but that's probably not a great idea if you plan on putting this on AMO or perhaps use it yourself

**Comment by igorlogius** [comment]
Some notes ... on closer inspecting the addon. Things that would need to be done

1. replace options page, needs two dynamic input tables 1) Format and 2) Variables (options.html)
2. DEFAULT_OPTIONS and VARIABLE_NAMES storage, needs modification from static keys to dynamic list/array (common.js+options.js)
3. some event handeling stuff needs changes/restructure (common.js+background.js) 
4. button popup needs modification for multiple formats (popup.html+popup.js)

**Comment by atomGit** [comment]
hello again igorlogius - so does this mean you've decided to take this project under your wing??? :)

**Comment by igorlogius** [comment]
i am considering it ... but i am not 100% sure ... dont want to make any promises, but if you see updates on this issue i am at least making notes and thinking of things todo or trying stuff out. We'll see how that goes. Life might get in the way soon, so i really dont want to make any promises.

**Comment by igorlogius** [comment]
i have to reject this request

i just dont see that i'll have the time to work myself into this addon or rebuild it (since it does has some complex logic built into it)

**Comment by Vingolf** [comment]
atomGit wrote:

> there's several similar add-ons on AMO, but none that are as good or as featured
> 
> there are key issues with the current version however...
> 
>     * limited format options (9)
> 
>     * inability to easily re-order format options
> 
>     * lacks a dark theme
> 
>     * no included guide/documentation

Consider to have a closer look on [Copy Selected Tabs to Clipboard](https://addons.mozilla.org/en-GB/firefox/addon/copy-selected-tabs-to-clipboar).

This addon has 

• more options, a limit is not specified,
• the ability to reorder format options.

It allows to work together with [Tree Style Tab](https://addons.mozilla.org/de/firefox/addon/tree-style-tab)  from the same author, Piro.

I'm using both addons and I am quite satisfied with Copy Selected Tabs to Clipbord.

Regards,
Vingolf

**Comment by atomGit** [comment]
hi @Vingolf - thanks for the tip but it doesn't look like that has the ability to copy or format selected text within a page
