### ISSUE TITLE
[Copy Tabs]: Third mouse button click not possible on Macbooks

### ISSUE THREAD

**Issue by norbsmaq** [igorlogius/igorlogius#33]
### Description

Using a Mac laptop with the touchpad, there is no "third mouse button click" so you cannot use the default action.  You are forced to use the menu every time now.  

The ability to set a default action based on left click on the icon was a better solution.  It would be great to have that functionality back or the option to enable it.

**Comment by norbsmaq** [comment]
Thanks for the quick reply.  I must've skipped right over the setting when I was looking at it.  I appreciate the work on the add on.  I use it all the time!

**Comment by igorlogius** [comment]
>  I must've skipped right over the setting when I was looking at it.

Might be ... but i did add that options a bit later ... so you might just have had a version without that option.

> I appreciate the work on the add on. I use it all the time!

Nice to hear that it's useful for someone else than just me. 
Let me know if you have any improvment suggestion ot find any bugs.

Until then i wish you all the best.
