### ISSUE TITLE
[Close Duplicate Tabs] ADD ability to disable autoscan + button for manual Duplicate Scan

### ISSUE THREAD

**Issue by allanlaal** [igorlogius/igorlogius#35]
### Description

[Close Duplicate Tabs](https://github.com/igorlogius/close-duplicate-tabs ) listening to all tab touching events will start to lagg Firefox with lotsa tabs

solution is a Manual Scan button to run dedup

**Comment by allanlaal** [comment]
also affects the most popular plugin: https://github.com/Peuj/duplicate-tabs-closer/issues/87

**Comment by igorlogius** [comment]
Interesting, my addon has a mechanic to reduce processing when many tab events are triggered in a short timeframe, ... but i'll see what i can do.

**Comment by igorlogius** [comment]
@allanlaal 

The tab state tracking is a bit to deeply integrated into this addon, but i could easily create a much simpler one, which only contains the duplicate counter+remover and hook those into user actions, like toolbar button clicks.

Only drawback would be that you'll lose somet of the extra functions, like `keeping oldest tabs`, `manually ignoring tabs`.

If thats fine with you i can share with you a version that technically should have no influence on performance in any way (until you manually trigger its processing)

**Comment by allanlaal** [comment]
@igorlogius even a single tab event is too much when you have hundreds of tabs

@igorlogius yeah, i saw that from the code , I'm writing a new one atm at https://github.com/allanlaal/browser-duplicate-tabs-closer-button (WIP)

**Comment by igorlogius** [comment]
Careful, the one that you forked doenst care about containers.

- https://github.com/igorlogius/count-duplicate-tabs
- https://addons.mozilla.org/firefox/addon/count-duplicate-tabs/

**Comment by igorlogius** [comment]
closing this issue, since the request is now covered by

https://github.com/igorlogius/count-duplicate-tabs

(If you have additional requirements, let me know via another issue)
