### ISSUE TITLE
[open-in-temp-container]:  open links to other domains in a new temp container tab with a single action

### ISSUE THREAD

**Issue by privacy-advo** [igorlogius/igorlogius#36]
### Description

First, thanks for this amazing addon.  
I heavily rely on the keyboard shortcut for "Open newtab in temp container" to speed up opening temp containers. But opening bookmarks and links via context entry is painfully slow. I wish open in a new temp container was the default for all links, bookmarks and so on. This would be particularly desirable for opening links from search engine results. You don't want to have the ten opened webpages from e.g. Google search results in the same container. Opening all of them via context entry is a real pain.

**Comment by igorlogius** [comment]
Hello @privacy-advo 

thanks for taking the time to give some feedback. 

Regarding your suggestion, OiTC has some advanced options, which are intentionally hidden, which might already cover your requirements. 

1. Goto the OiTC's preferences pages 

2. Click the yellow warning icon `/_!_\`, in the lower right corner to reveal the advanced options. 

    ![2024-07-27_11-58](https://github.com/user-attachments/assets/390e6d4c-9465-4c60-a0eb-7c72da7ea098)

2. Change the "Operation Mode" from "Open only URLs matching in temp container" to  "Open Everything not matching in a temp container"

    ![2024-07-27_11-59](https://github.com/user-attachments/assets/47348355-66c3-4c4f-8fef-0caa0cd07d64)


The textareas directly below allows you to define exceptions ( in your case for sites you dont want to automatically open in a temp container. )

Hope this info helps, but if not, feel free to clarify your suggestion and i'll take another look.

**Comment by privacy-advo** [comment]
Thanks for the detailled feedback. The icon is quite small at 4K, so I missed it, unfortunately. Great to see there are advanced options. Changing to "Open everything not matching in a temp container" provides the desired behaviour for opening bookmarks and new tabs. Love that.

The search engine issue:
How can I open links to other domains in a new temp container tab with a single action?

**Comment by igorlogius** [comment]
> How can I open links to other domains in a new temp container tab with a single action?

Please try `"version": "1.1.37"`, it adds localized origin awareness in a localized tab scope. 
(meaning Tmp containser are not matched with domains, but if a Tmp container is created from another Temp container the container will only be retained of the origin is thes same)  

https://github.com/user-attachments/assets/87d679dd-c87a-47db-80da-8800a40fe662

**Comment by privacy-advo** [comment]
Amazing work. Thanks.
It is now safe to say that OiTC is a fully-fledged replacement for ~90% of the sadly discontinued stoically's [Temporary Containers](https://github.com/stoically/temporary-containers) users.
