### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by Ceyarrecks** [igorlogius/igorlogius#37]
### Question

What means are available in which to financially say: THANK YOU!! for this most-excellent FF Add-on in the form of Load Background Tabs On Select that actually works to bring FF back into sanity. 
Again, Thank You for your time in preparing this add-on and the time taken to reply.
HCA

**Comment by igorlogius** [comment]
Hello @Ceyarrecks,

thank you for taking the time to write this feedback. 
It's nice hearing that one of the addons is useful to you. 

Regarding donations, if you want you can send a `small tip` (for a coffee or a beer) to the following bitcoin address `35WK2GqZHPutywCdbHKa9BQ52GND3Pd6h4`

If you use a mobile wallet app, you can scan this qrcode to transfer the address hash easily.

![35WK2GqZHPutywCdbHKa9BQ52GND3Pd6h4(2)](https://github.com/user-attachments/assets/3269cec1-54d3-4eb4-8c84-6dd62114de0e)

If you dont have a wallet dont feel pressured to create one or anything, 
instead just write a short review on AMO. That's good enough for me too.   

Thanks again and have an awesome day/night!
