### ISSUE TITLE
[Open in Temp container]: request permissions on demand

### ISSUE THREAD

**Issue by totallynotbillgates** [igorlogius/igorlogius#38]
### Description

Feature request: ask for the additional permissions on demand when we click "Bookmarks" or "History", like this other extension:

https://addons.mozilla.org/fr/firefox/addon/temporary-containers/
https://github.com/stoically/temporary-containers/blob/main/src/ui/components/advanced/deletehistory.vue#L51

![ad](https://github.com/user-attachments/assets/71750ea8-9c3e-437c-9b40-deafd0bc7831)

**Comment by igorlogius** [comment]
I guess having all options on one screen a little more userfriendly.

From a dev standpoint it just feels a little unnecessary/redundant, since the permission switches are only one click away.

**Comment by igorlogius** [comment]
Done `1.1.40`

![2024-07-29_19-56](https://github.com/user-attachments/assets/d2f0557f-43ad-4a4c-838e-caf7863ee3f3)
