### ISSUE TITLE
Automate Click Extension 

### ISSUE THREAD

**Issue by Whoami-ZG** [igorlogius/igorlogius#4]
Dear Igorlogius, 

I would like to start by saying thank you for developing the extension "Automate Click".

I have been using it as a help to pick up chats in my part-time chat support job. I really rely on this job and on the chat bonus to survive as a student. 

I used to have it but it has been taken down recently and I cannot find it. Is it possible to help me restore it and get it running once again? 

Thank you many times in advance. 

Best Regards.

**Comment by Whoami-ZG** [comment]
I found the archived link 

https://github.com/igorlogius/not-on-amo/blob/main/automate_click-1.14.7.xpi

And I like yours better than Automa for the record xD

Thank you a million times.

**Comment by igorlogius** [comment]
Sorry for the confusion, i just genuinly think that people will be better of using Automa in the long run and didn't see myself competing with it (aka. adding all those features to AC) that automa already has.
But i guess if you dont need all the extra stuff, feel free to continue using AC.
If you find bugs, you can also report them and i'll try to fix them, but i just wont be adding any new features.
