### ISSUE TITLE
[load-background-tabs-on-select]: Add a checkbox to disable all rules temporarily

### ISSUE THREAD

**Issue by eight04** [igorlogius/igorlogius#40]
### Description

Usually I use the extension in blacklist mode, so some sites are not loaded by default.

However, there are some cases I would like to preload them in the background. I have to:

1. Go to about:addons
2. Find the addon
3. Disable the extension

After my tasks are done, I have to do it again:

1. Go to about:addons
2. Find the addon
3. Enable the extension

---

I suggest adding a checkbox to browser action menu so the workflow can be simplified:

1. Right click the browser action
2. Check/Uncheck "Disable temporarily"

**Comment by igorlogius** [comment]
Sounds like a good idea. 
I'll see what i can do.

**Comment by igorlogius** [comment]
Function added to version `1.2.6`
