### ISSUE TITLE
Automate Click: add clicking on elements in closed shadowRoots (used in cloudflare captures) 

### ISSUE THREAD

**Issue by greenozon** [igorlogius/igorlogius#41]
### Steps to Reproduce

Hi!
Is it possible to add support for this element?

![image](https://github.com/user-attachments/assets/1ab4b13d-269c-4cda-add0-12fa99b0fb7d)

whatever I did - it just does not click that checkbox...

### Expected Result

Checkbox is clicked

### Actual Result

nothing hapens

### Additional Information

the CSS selectors looks very small:
 .cb-lb

**Comment by igorlogius** [comment]
This should already work.
If the selector is correct and the checkbox is not disabled, then triggering the onclick function on the input[type="checkbox"] elment will set the setbox to checked (value:="on")

test it here:

- [ ] try to check me, my selector is `.task-list-item-checkbox`

**Comment by greenozon** [comment]
thanks for fast reply!

I've the following setup:

![image](https://github.com/user-attachments/assets/746ef676-ba4e-45af-aa92-4dff0ace596c)

I saved it then go back to this page, hit F5 and nothing happens
but to be honest I'm also not able to check that checkbox using mouse...
most probably it is R/O for me as I'm not the author of that post

I hope you won't mind if I'll put a local test here for my self :)

- [ ] Mercury
- [x] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars
- [ ] Jupiter
- [ ] Saturn
- [ ] Uranus
- [ ] Neptune

**Comment by greenozon** [comment]
Well, the above sample works! thanks,
but the initial task still not...

here is a demo page that has that nasty  checkbox from C.F.:
https://2captcha.com/demo/cloudflare-turnstile

I tried both checkbox itself as well as label to the right  (and put 9 seconds initial delay) - no effect! just nothing... :(

**Comment by igorlogius** [comment]
mmh, while the capture is inside an iFrame, AC already has an mechanic that should inject the content script into all iFrames, but it does not seem to work in this case.

i'll need to experimenting a bit to find out what the reason for this is. 
It could be a firefox bug ... or something related to the "late iframe inclusion via AJAX". 

I'll try and find out and be back later.

**Comment by igorlogius** [comment]
Seems like i was mistaken ... the issue is not iframe related, but the elements are actually not part of the "normal DOM" but inside of the so called "shadow DOM".

Thats a bit unusual ... i need to see if i can modify AC to also query the shadow DOM ... i kno w i have done something like this in the past ... i just need to find it again and see if i can work it into AC. 

This is turning out to be a bit more involve than i suspected. 

Be back later.

**Comment by greenozon** [comment]
Thank you so much for spending time in this new case
this sounds like you just knocked the "Matrix door" :)

crossing fingers!
:smiley:

**Comment by igorlogius** [comment]
This issue has multiple challenges

![2024-08-17_19-43](https://github.com/user-attachments/assets/442e6d78-a02e-44c9-85d0-60e14d6218c3)

1. iframe (should not be an issue
2. closed shadowDOM (this seems to be more problematic )

i did find possible solutions for the closed shadowDOM ... but i could not get them to work with AC yet.

Not making any promises, but i'll leave this issue open for now and maybe take another look at this.

Redeclaring this into a feature request to Support "Closed Shadow DOM Elements"

**Comment by igorlogius** [comment]
Some refs

- Testpage: https://2captcha.com/demo/cloudflare-turnstile
- https://stackoverflow.com/questions/57813144/how-to-select-element-inside-open-shadow-dom-from-document
- https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM
- https://stackoverflow.com/questions/54954383/override-element-prototype-attachshadow-using-chrome-extension/54954525#54954525

**Comment by greenozon** [comment]
Hi there!
whats up!

Is there smth I could help on this?....
some observations:
1) usually you could reach out almost all elements on the HTML page by using TAB button, but, for some reason it is not tab-ing over that checkbox and label!
2) found similar case over here: https://github.com/AutomaApp/automa/issues/1725
they are mentioning some debug mode... might that be in handy?

**Comment by igorlogius** [comment]
> whats up!

Busy with life ATM. 

> Is there smth I could help on this?.

Nothing i can think of. Bsically i have everything i need, but its just not easy to include the shadowRoot without making some major changes to the  entire addon, which i frankly dont have the motivation todo at the moment.   

Automa already seems to covers the shadowRoot situation. At least from what i see in their repo. 

ref. https://github.com/AutomaApp/automa/blob/d8c16d5d2f89520a0d2ec63db336b8e6b35ffca4/src/lib/query-selector-shadow-dom/index.js#L208

I'd suggest you migrate from AC to Automa for your usecase, since i dont know when or if will look into this. 

Sorry for getting your hopes up.

**Comment by greenozon** [comment]
ok, thanks for fast answer
good luck with life cases and sorry bothering
anyway this addon rocks!

**Comment by greenozon** [comment]
Hmm, looks like Autom is also kind of limited in it's features, eg:

![image](https://github.com/user-attachments/assets/24523c05-4c52-4a20-8dd1-858cdfa8e924)


as I'm Firefox user, so it is not OK...

hi btw!
whats up! :)

**Comment by igorlogius** [comment]
Thats interesting ... maybe there is some other issue with this ... i might have to get in contact with one of the Automa devs ask.

> hi btw! whats up! :)

Not much, I was only doing some cleanup, nothing to see here, sorry.

**Comment by igorlogius** [comment]
Seems like the late inclusion of the iframe via ajax is causing addional problems. 

I am done with this fucked API (shadowDOM) for the moment and personally hope it will be removed from the web-standard specification rather sooner than later.
