### ISSUE TITLE
Copy Tabs: Flip LMB and MMB Action Broke

### ISSUE THREAD

**Issue by SandmanPSU** [igorlogius/igorlogius#42]
### Steps to Reproduce

The "Filp LMB and MMB action on the toolbar button" option is not working correctly with latest update. With this option checked, both the LMB and MMB action produces the same result with bringing up the context button menu with all the Copy Tabs options.

### Expected Result

With the option checked, the LBM should do the set third mouse button action.

### Actual Result

With the option checked, the LBM brings up the context button menu with all the Copy Tabs options.

**Comment by igorlogius** [comment]
That sounds bad, i'll check.

**Comment by igorlogius** [comment]
version `1.16.53` should fix the issue.
