### ISSUE TITLE
[Open in Temp Container] add option to change the Same Origin policy

### ISSUE THREAD

**Issue by makovich** [igorlogius/igorlogius#43]
Hey!

It turns out that last update changed [my workflow](https://xkcd.com/1172/) a bit. I use TC with `C-Space` to create a new tab whenever I'd like to dig into any research. Starting typically from Google I then open up a tree of links. Those are definitely from other origin so it ends up with multiple new containers. Same thing happens when, for instance, if one's project documentation lives on another TLD. That spins up more containers slowing down things much as in xkcd joke. :)

Looking through code, I noticed [changes](https://github.com/igorlogius/open-in-temp-container/commit/820e3e848568d48706ce9d8a7b02bdc230a71100#diff-bb06783fccd762e4d905ab922491e954a9fbaf708a1acbf53dff92872b0bcd3bR353) that, probably, affect this behavior. So the question/suggestion: could the option hide it? Would you prefer PR from me?

Thank you for the nice extension! Great balance between simplicity and functionality for the now.

**Comment by makovich** [comment]
_Wrong hole! Thank you GH redirect!_

**Comment by igorlogius** [comment]
Hi! Thank you for opening this issue and providing feedback.

Now about your issue. i understand your usecase and i agree the  
simplest solution would be to add an option to change the behaviour to let child tabs spawned from temp containers remain in the same container.

The origin separation still seems to me like it would be something other users would want/expect, so i'll keep that as the default for now.

**Comment by makovich** [comment]
Here it is If it works for you: https://github.com/igorlogius/open-in-temp-container/pull/18.

**Comment by makovich** [comment]
Thank you so much! ❤️
