### ISSUE TITLE
[Open in Temp Container] Automatic Temp Containers

### ISSUE THREAD

**Issue by knghtbrd** [igorlogius/igorlogius#44]
### Description

For years, I have used the extension Temporary Containers. I've gotta say, the extension is a bit complex in the things it can do, and I do not use it to its fullest, but I do use the automatic temporary containers feature. And … sadly, its author has died with AFAICT nobody having commit rights. It's a matter of time before the extension becomes unsafe to use or incompatible with the latest FF.

The biggest feature of it for me is that one can, if one chooses to, enable automatic temporary containers. When you use the + or ^T to open a new tab, you get a new temporary container automatically. There's fine-grained controls to try and isolate sites in their containers, but I mostly do not use these.

When using automatic temporary containers, data and cookies ONLY persist if you open the site deliberately in another named non-temporary container, because the "no container" will only be used for "internal" sites opened by the browser, extension preferences, that kind of thing. The upshot of this is that if you care about the site info/storage/cookies/etc, you have to explicitly have/use a container for that site.

Which is fine, it makes every page effectively an ephemeral private-browsing window unless you explicitly opt-in to it being otherwise. The perfect default if you know how to do that! Everything else, 5 min (default 15) after I close the tab(s) associated with that temp container, the data/storage/cookies/etc for it are gone. The delay allows for an "oops" un-close of an accidentally closed tab to not require starting over, but otherwise …

I said I didn't use the isolation rules until recently. I often middle-click links to force them into a new tab. One of the isolation rules allows me to make the middle-clicked link use a new temporary tab if the link does not match the domain and subdomain of the current page. But I can right-click and "open in new temporary container" if I care—turning on the rule just allows a little more laziness. 😁

I'm not really a JS person but I'd be happy to contribute to development of this feature. This is a little rambly and disorganized as a feature request, but I've done both support and dev work elsewhere so actual bug reports should hopefully be more useful and to the point, at least.

Hope you'll consider this one as … nothing else does what temporary containers does, currently.

**Comment by igorlogius** [comment]
Hi, thanks for taking the time open this issue.

I am not 100% sure i understand your suggestion(s) completely,
but it seems like you are suggesting more fine grained control over when a new temp container should be created.

> middle-click links to force them into a new tab. One of the isolation rules allows me to make the middle-clicked link use a new temporary tab if the link does not match the domain 

This description sounds like `Implicit Automatic Mode` with "Same-origin policy" enabled

https://github.com/user-attachments/assets/0ab140a0-655b-4614-a17e-91b2099833d8


If this is not what you mean, you'll have to explain it to me again, sorry.

**Comment by igorlogius** [comment]
@knghtbrd 

Does this cover your usecase?

**Comment by knghtbrd** [comment]
It does, thanks! (The other part was me doing something stupid and not understanding how automatic mode was intended to be used. 😅 PICNIC concluded.)
