### ISSUE TITLE
[Save Website as Image]: Automate saving with  date/timestamp

### ISSUE THREAD

**Issue by 3mandd** [igorlogius/igorlogius#45]
### Description

Thank you for this awesome addon!
Would be real cool to add some automatic capturing options.

Automatically:
-Take screen shot of every website visited.
-Take screenshot every X amount of time in current tab.

This would help to fight websites/companies wrestling control/data/info  away from users and allow to recover potentially lost work/efforts.

**Comment by igorlogius** [comment]
Hi @3mandd,
thank your for taking the time to give some feedback.

While automatic screenshots are doable, there are some rather "tricky" things here and the option itself feels like it would invoke additional requests, like "duplicate removal", "black/whitelist" of websites ... and maybe much more. 

That is why i am hesitant to add this to the existing addon that already has quite a few users.

I'd rather fork a new addon where we can experiment with some of these features first.

**Comment by igorlogius** [comment]
Some preliminary thoughts/notes: 

> Take screen shot of every website visited.

*UI*

- a on/off shortcut should be fine  ( with a notifiction or badge icon change )
- (optional) input field to configure the output: `YYYY-MM-DD hh:mm:ss - urlencoded(url.origin+path+params+hash).extension (jpg,png,cbz)` 

*Behaviour*

If a website has been fully loaded (no pending network requests) and lets say the page/tab has been unchanged (stable url) for at least 5 seconds (option?) then a screenshot will be created.


> Take screenshot every X amount of time in current tab.

*UI*

- some timer inputs on the options page 
- some shotcuts to start/stop each timer

*Behaviour*

only one timer can/should be active at all times.


For both automatic screenshot options the should be a way to make Exclusions / Inclusions of Sites. Assuming people dont want to screenshot every website, like stuff they visit regularly , we want some kind of exclusion list. Also assuming some people would rather want to only snapshot specific websites, those would rather want an inclusion list.

*UI* 

- `checkbox/toggle for black/whitelist` 
- textarea input for url regex matches for inclusion/exclusion

*Behaviour*

Only one mode (includsion/exclusion) can be active.

**Comment by 3mandd** [comment]
Thank you igorlogius.

" configure the output: YYYY-MM-DD hh:mm:ss"     - yesss, exactly.

"if a website has been fully loaded (no pending network requests)"   - actually would be nice to capture  as-is, regardless of completion - want to keep that for same reason as: the "duplicates".

I have been trying to find a way to keep browsing log in a "court-admissible" way.
This isn't new, and there are ways  ( https://github.com/awesome-selfhosted/awesome-selfhosted#archiving-and-digital-preservation-dp )

But your method is robust and simple. Moreover it would capture browsing "as it was". Like a security camera.

While other tools might save text/media in complex way, they can not reliably guarantee to restore it the way it was,( unlike a simple picture capture). Ultimately consuming a lot more resources and being less reliable then a picture capturing tool 

Case Scenario:  I am applying for a service with a fishy company. Application form is all secured, multiple steps etc. They make promises while application form, and deny after.

I now have a bunch of  .JPEGs  that can potentially be used as admissible evidence and court.

So in essence a simple timer and duplicate redundant automatic browser picture hammer, can be very effective.

Any lost info/text/form data by accident (click next/back button while filing a form)  can also be easily recovered by going OTR on jpegs.  (there's a nice "Form History Control" addon for now)

Perhaps to keep it sane, picture taking pattern can be triggered by  any user input/change in hast specific tab.

So take a picture of every url visited, and every active tab that's being used @ user set rate  6captures/min or something.

**Comment by igorlogius** [comment]
Thinking a bit more about your proposed usecase, wouldn't a screenrecorder application like OBS be a better solution? - You can capture individual windows and with the correct configuration capture into whatever format you want. I think there might even be plugins, that allow to autostart a capture , like when an application is started or something. 

This might not be the easiest solution and an addon that captures a trail of your browsing might be simpler to use and good enough, but i think i'll keep it as simple as i can in light of that if people want more control over the capture that they should switch over the better solution.

**Comment by igorlogius** [comment]
https://github.com/user-attachments/assets/c31c357d-6656-469c-9d17-f9e670734435

**Comment by 3mandd** [comment]
Screen recorder only captures what's visible, as opposing to static document of the entire page.
OBS and other are more resource intense, need more user permissions to install and run - as opposing tool that can travel with you cross pc via Firefox browser/cloud.
This would always work when  firefox is launched and you wouldn't forget not to turn it on and yet again miss that info that you just had!!

Example: Click on comment, post, a preview of which you just seen, but it's deleted, you go back hoping to at least get all info preview you just seen, but  it's gone as well - because many now design sites with that intention. 
 just want to keep what I've seen already. 

but I get that you want  "keep it as simple as possible", and clearly been successful at that!

perhaps it would be a different tool:

auto-starting, variable timer,  picture taking firefox add-on -capturing user activated tabs at set rate in firefox anytime firefox is running.
. sorta  Simple-FF-Browser-Activity-Camera

**Comment by 3mandd** [comment]
there used to be a bunch of HTML autosaving addons like
https://addons.mozilla.org/en-US/firefox/addon/auto-save-html/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

but they where not reliable and would capture data in ways that could not be recreated in a shape as it was/seen.

and after firefox15 most of them never worked.

Auto Save Firefox Browsing,
so  like FireFox history,
 but in multiple Pictures

**Comment by igorlogius** [comment]
I can add a auto-start option, no problem - just dont come complaining when your storage space runs out. :smile:  

Capturing HTML reliably is not as easy as one might think, especially with the kind of dynamic pages we have today. That is "kind of" a similar reason why i decided to not trigger the snapshots via change-events and only use a simple delay timer.

When the AMO Submit Process is done, you'll find the addon here: 

https://addons.mozilla.org/firefox/addon/automatic-snapshots/

**Comment by 3mandd** [comment]
Awesome!
Will give it a run.

Thank you igorlogius, really.


Wayback machine don't work most places now. 


This type of add-ons will too also fall victims to data hogging soon enough as all going to be encrypted and made impossible to capture.

Good example android apps ability to block screen-shot taking.

Them corps will do anything to have data and to make sure that no one else gets any. 
Call them oh phone?, they'll record it. Try recording the call yourself, impossible. 
Last time this was possible was prior to Android 8.

Many websites now purposely allow only a single TAB so that user track keeping is limited. It's funny how they'll claim it's for security/the way site works, but than you see them posting: https://stackoverflow.com/questions/33769330/how-to-prevent-same-website-open-multiple-tab-pages

**Comment by 3mandd** [comment]
![image](https://github.com/user-attachments/assets/8db1894b-2e72-4145-aee9-b292dc304493)

**Comment by igorlogius** [comment]
@3mandd 

Available on AMO now

https://addons.mozilla.org/firefox/addon/automatic-snapshots/

I still need to add the autostart options, but you want, you can already test it out.

**Comment by 3mandd** [comment]
Way awesome. But it takes a window section snapshot only, not the entire page like "Save Website as Image"

**Comment by 3mandd** [comment]
Thank you igorlogius!
even with window section snapshot only, i am already going to be running it forever.

**Comment by 3mandd** [comment]
The red on indicator showing that it's on is great
would be really cool if the "Save Website as Image" addon icon (in firefox toolbar)  can blink red every time it captures, confirming that it's working.

**Comment by igorlogius** [comment]
>  it takes a window section snapshot only, not the entire page 

Well, since the addon already likely creates quite a lot of duplicates, i thought it would be better to only save the visible area but if you really want, i can change it.

>   icon (in firefox toolbar) can blink red every time it captures,

That is doable but wouldn't that be a bit to distracting?

**Comment by 3mandd** [comment]
That is doable but wouldn't that be a bit to distracting? 
it's like a camera recording red indicator light. 
distracting~reassuring - for whom how.

Automatic Snapshots  - Simple Forensic Firefox Browsing Tracker  - AutoSaveX  

AutoSaveX   because that's what these things where generally called, someone first made a website saving addon, then someone else added more features to it, and then someone else added a timer/auto launcher to it. so there was like 10-15 addons all called autosave/autosavex.  So a bunch of  ppl who looking for this sorta thing, going to search "autosavex".
but lol at all that, because simple picture snapping would have yielded same data in a much better organized structure. .
as opposing to storing stuff by filetype -- oh lol

**Comment by igorlogius** [comment]
speaking of filetype, you are aware that the method used to save a whole websites doenst always produce an image ... that is currently an imposed limit by the browser built-in canvas API, which doenst allow to take images larger than a certain amount of pixels, the workaround that 'save-website-as-image' uses is to segment the website into multiple images and save them as an cbz/zip archive. 

Just mentionaing this, since it might make your post processing of the images somewhat more difficult.

**Comment by igorlogius** [comment]
Closing this issue, since the request basic request has been fullfilled.

Version 1.0.1 of automatic-snapshots  adds the requested
"shutter feedback" and the "activation is now saved" between browser restarts.

**Comment by 3mandd** [comment]
Awesome, thank you so much.

**Comment by igorlogius** [comment]
@3mandd  

Let me know if you find any bugs or have other improvement suggestions.
I'll fix up the AMO page when i have some more time and motivation over.
