### ISSUE TITLE
"Copy Text" has stopped working

### ISSUE THREAD

**Issue by todapop** [igorlogius/igorlogius#46]
### Steps to Reproduce

https://finance.yahoo.com/quotes/FXAIX,DHR,TM,LAD,FI,UBER,APO
Click Table to CSV to form outlines
Right click and select "Copy Text"

### Expected Result

Expect table to be copied to clipboard in CSVformat.

### Actual Result

Clipboard is blank. Nothing copied.

### Additional Information

I can export as text and open the file to copy the table.  This is only a workaround.

**Comment by igorlogius** [comment]
Thanks for reporting this.

Looks like the firefox devs changed something in regards to the useraction

![image](https://github.com/user-attachments/assets/10418540-93c9-472c-a7a6-5bdc89138ae0)

I'll see what i can do to fix this.

**Comment by igorlogius** [comment]
I think i found a workaround.

I'll push an update shortly.

**Comment by igorlogius** [comment]
`1.3.24`

https://github.com/user-attachments/assets/970e427f-42b9-43df-8cf2-09dcfbc78705

**Comment by todapop** [comment]
Thank you for correcting this, everything is working once again ;-)
