### ISSUE TITLE
Auto Close Tabs: Whitelist doesn't work

### ISSUE THREAD

**Issue by StOrmCatz** [igorlogius/igorlogius#48]
### Steps to Reproduce

1. Addon configuration
Minimal number of tabs: 1
Amount of time until a tab is closed: 3 Minutes
Autostart: Yes
Whitelist: Add and Enable the following Regular Expression Matcher: .\*google.\*
2. Click Save Changes in Whitelist
3. Open 4 separate tabs to google.com
4. Open 1 tab to reddit.com

### Expected Result

After 3 minutes when the timeout has been reached:
- 4 google.com tabs remain open
- Single reddit.com tab is closed

### Actual Result

- All the google.com tabs are closed even though it should be whitelisted
- The reddit.com stays open because it's the minimal number of tabs

It seems as if the the whitelist rules are being ignored altogether

### Additional Information

I'm using WaterFox G6.0.19 which is a FireFox fork

**Comment by igorlogius** [comment]
@StOrmCatz  

Thanks for reporting this issue.

I've looked into this and i think i found the problem. - i used a function that doenst support Promises which caused the filter to now always work as expected. 

I now replaced the function with one that supports Promises and now the filtering should work. 

I'll release a new version shortly. 

Please let me know if that version resolves the problem for you.

**Comment by igorlogius** [comment]
version `1.7.20` should fix the issue

**Comment by igorlogius** [comment]
@StOrmCatz 

I hope everything is now working for you as intended. 
If you're still having issue, please let me know.

**Comment by StOrmCatz** [comment]
@igorlogius 

Thank you very much for fixing the issue and for such a quick turn around!  I've been testing it the past few days and the whitelist seems to be working great now!

I do have a question.  Under "Consider tabs which are ...",  what does it mean when a tab is "Focused"?

**Comment by igorlogius** [comment]
@StOrmCatz 

Glad to here that it's working for you.

> what does it mean when a tab is "Focused"

It refers to the "active" tabs in a windows. - Focused might not have been the best label for this.

By selecting this option, you remove the `"active":false` restriction, 
which allows the addon to consider all active tabs (like those in inactive windows), which  basically allows the addon to close windows if all tabs inside a window meet all other cleanup requirements.
