### ISSUE TITLE
[Find in Tabs]: Selected text in page deselects itself

### ISSUE THREAD

**Issue by CamiloFBL** [igorlogius/igorlogius#49]
### Steps to Reproduce

1. Select a text in a webpage you want to copy, want to do right-click on it, etc.
2. Wait a 1-2 seconds
3. Selected text get cleared

### Expected Result

Selected text should stay selected

### Actual Result

Selected text is no longer selected after 1-2 seconds

### Additional Information

I noticed this behavior after updating my addons on firefox. After deactivating each one, I noticed this addon was the culprit of this issue.

**Comment by igorlogius** [comment]
@CamiloFBL 

Hi, thanks for getting in touch. 

The addon uses the window.selection api to update it internal search text cache, this is likely the cause of the de-selection. 

Normally the cache update should only happend if a page change is detected, but i guess ... with modern websites ... that happens more often then necessary. 

I guess one option would be to completely remove the caching mechanic, at some performance loss. 


The update should only happend when the page is manipulated in some way, so i guess

**Comment by igorlogius** [comment]
Version `1.1.14` is now available. 

Deselection should not happen unless a search is started now.

@CamiloFBL: Please let me know if it works for you.

**Comment by CamiloFBL** [comment]
Tested and it works, thanks.
