### ISSUE TITLE
[Open in Temp Container]: History is not deleted after closing the tab with the temporary container

### ISSUE THREAD

**Issue by gabeweb** [igorlogius/igorlogius#51]
### Steps to Reproduce

1. Open a temporary container
2. Browse any website
3. While browsing, open the Firefox History panel to view your browsing history
4. While holding the tab with the temporary container open, you can see that the history deletes items every 10 seconds (the current time by default).

### Expected Result

Although history items are deleted while the tab with the temporary container is open, if the 10 seconds are not waited or the container closing is detected, the extension should be able to delete history items automatically or over time default as if the tab was still open.

### Actual Result

1. If you close the tab with the temporary container early, Firefox history retains items that couldn't be deleted before closing the temporary container.

### Additional Information

2. Firefox Developer 131.0b8 (64-bit) Windows 10
3. Open in Temp Container 1.1.47

**Comment by igorlogius** [comment]
I am fairly certain that history deletion does not depend on tab existens, but i'll try and reproduce this issue.

**Comment by igorlogius** [comment]
Please have a look at this capture and make sure i correctly followed your steps. 
If not, let me know and i'll try again. 

[demo-2024-09-20_23.58.21.webm](https://github.com/user-attachments/assets/afe7de2c-cacb-4a18-b61f-4b9ee9fcbd6b)

As far as i can tell everthing seems to works as intended. - Every 30 seconds half the temp history that was generated by any temporary containers gets removed, until no history is left. 
Doesnt matter if the generating or any temporary tab still exists or not. Sidenote: If the browser gets closed before the history is fully cleaned, the process just continues the next time when the browser is re-started.

**Comment by gabeweb** [comment]
@igorlogius 

Sorry, you're right. The delay time is set on 30 seconds even after been closed the temporary container.

**Comment by igorlogius** [comment]
@gabeweb
