### ISSUE TITLE
Find in Tabs: Cannot search open PDFs

### ISSUE THREAD

**Issue by ChiefArug** [igorlogius/igorlogius#56]
### Can you reproduce the issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

None

### Steps to Reproduce

Have a PDF open in a tab and attempt to search using the addon.

### Expected Result

Results to show from the PDF.

### Actual Result

No results.

I assume this is due to the PDF viewer being a 'restricted' page that FF disables addons on, but on the off chance something can be done about this (even if it involves the user having to do something) I though I might as well report it anyway.

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to open this issue.

Sadly i am also not aware that there is anything that can be done to allow addons to work on these PDF pages at the moment, sorry. 

Might be worth opening a request on bugzilla or connect.
