### ISSUE TITLE
Auto Close Tabs: an option to ignore pinned tabs

### ISSUE THREAD

**Issue by hoangdinhini** [igorlogius/igorlogius#58]
### Describe your request or suggestion

- I want to have an option to ignore pinned tabs, so my pinned tabs would not be closed after some time.

Thanks!

**Comment by igorlogius** [comment]
Hi, thanks for opening this issue.

Pinned tabs should not be considered unless you checked the option for it. 
If pinned tabs get closed without having that option checked, then i'd consider this a bug. 

![image](https://github.com/user-attachments/assets/9292932d-2795-43ef-ac9a-b085657872f6)
src: https://github.com/igorlogius/auto-close-tabs/blob/691028b3141265a959a27a89b1779ee44554c8e5/background.js#L69

**Comment by igorlogius** [comment]
no feedback/steps to reproduce, closing for now
