### ISSUE TITLE
Link Extras: duplicate menu entries 

### ISSUE THREAD

**Issue by siffegh** [igorlogius/igorlogius#59]
### Can you reproduce the issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

yes - Please only select if you actually did!

### Steps to Reproduce

- install add-on
- R. click a link > click Link Extras

### Expected Result

Seven options should appear.

### Actual Result

There are some extra things above the seven options.

![](https://github.com/user-attachments/assets/aac9c3a2-fdee-42d7-a9f2-6c23e160bd5f)

**Comment by igorlogius** [comment]
Damn, that looks a broken. 

There are only supposed to be 3 extra options "open, close and download".

No idea how i missed that, but i'll fix it asap.

**Comment by siffegh** [comment]
There are only three extras on my working profile, beta, and nightly. The duplication is only on a new install.

What are those options supposed to do, anyway?

**Comment by igorlogius** [comment]
> The duplication is only on a new install.

yeah, it seems this is something timing related ... Shouldn't be to difficult to fix, but it's kind of annoying to not be able to use the debugging tools for testing and instead having to sideload the extension each time.

> What are those options supposed to do, anyway?

Those options should be useful when dealing with mutlple links (in a selection)
They allow to execute the mentioned action on alle links at once

- "Opening the link targets in tabs"
- "Close tabs which have the same urls as the selected/marked links"
- "Download the link targets immediately (without prompting for input)

These actions divert from the inital intent of this addon but i thought they  might be sufficently useful to have at hand, when dealing with links. 

For users who mainly use the addon to on single links, this might be a bit annoying to have those options at the top ... and i am still thinking about how to best deal with that. 

To mitigate that, i might have to make them configurable (hide, sortable) via the preferences in the next version.

**Comment by siffegh** [comment]
>To mitigate that, i might have to make them configurable (hide, sortable) via the preferences in the next version.

That's what my next issue would be, as now I really only use it for markdown. Tried the other new options which might be useful though, so either sortable or hideable would work.

**Comment by igorlogius** [comment]
> so either sortable or hideable would work.

I'll see what i can do.

PS: the duplication issue should be fixed with 1.4.10

**Comment by igorlogius** [comment]
![2024-10-24_03-00](https://github.com/user-attachments/assets/847c6890-a772-47c3-bf91-dd60b88fc211)

Hope this is acceptable for you. 

Please also be aware that you can assign custom shortcuts to your most frequently used actions so you dont have to open the context menu for those each time. 

![image](https://github.com/user-attachments/assets/33a2092c-3823-4402-80b6-b3835ec1a83e)
