### ISSUE TITLE
Link Extras: Wrong `homepage_url` and Clarification Needed on New Permissions

### ISSUE THREAD

**Issue by patate254** [igorlogius/igorlogius#60]
### Describe your request or suggestion

Hello,

I appreciate the hard work and usefulness of the "Link Extras" extension, which I use extensively. However, I recently encountered an issue that raised some concerns.

During the latest update, Firefox notified me that the new version of "Link Extras" requires approval for additional permissions:

- Download files and read and modify the browser’s download history
- Access browser tabs

To understand the necessity of these new permissions, I checked the extension's description in `about:addons`, but I couldn't find any explanation or feature listing that would justify these permissions. Additionally, the update notes were not available, and the home page link provided in the description led to a "page not found" error.

Upon reviewing the [manifest.json file here](https://raw.githubusercontent.com/igorlogius/link-extras/refs/heads/main/manifest.json), I noticed that the `homepage_url` is incorrectly set to [https://github.com/igorlogis](https://github.com/igorlogis). It should be corrected to [https://github.com/igorlogius](https://github.com/igorlogius).

Also, I would like to suggest that the extension's description or update notes be updated to reflect the new features introduced in the commit from Oct. 21, 2024, such as:

- The ability to open and close tabs
- The ability to download files

Including these details in the description or update notes would help justify the need for the new permissions and reassure users like myself.

Thank you for your attention to this matter.

**Comment by igorlogius** [comment]
Thanks for the input. 
I'll fix up the issues you mentioned.

**Comment by igorlogius** [comment]
- homepage_url [x]

- Added a Developer note on the AMO page

![image](https://github.com/user-attachments/assets/28e44f1e-3d1e-44ff-8fc5-6a1c2e187c15)
