### ISSUE TITLE
Bookmark Branch Porter: import of HTML & JSON not working ( FF 130.0.1 + BBP 1.4.18 )

### ISSUE THREAD

**Issue by ericmarceau-rogers** [igorlogius/igorlogius#62]
### Can you reproduce the issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

None

### Steps to Reproduce

Suspected incompatibility introduced following update of Firefox to newer version(s).

Unable to import using options
- import JSON
- import HTML

Attempted **multiple** times, single-level branch (5 URLs) and multi-level branch (3 subdirs with about 10 URLs each) using
- export Branch JSON
- export Branch HTML

Action applied to exported file before importing:
global replace of a fixed string     z-library.sk   ->  z-lib.gs
no other changes in output

Then imported using 
- import Branch JSON
- import Branch HTML

```
Bookmark Branch Porter version:
1.4.18

Current Firefox version:
130.0.1 (64-bit)  (mozilla-deb - 1.0)

OS:
UbuntuMATE 22.04.1

uname -a
Linux OasisMega1 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC
```

### Expected Result

Correctly importing Bookmark Branch from file.

Method:
- (preferrably) Import Branch JSON
- (or) Import Branch HTML

### Actual Result

no messaging !!!

Recommendation:
- Window that is used to select file to import should remain open and display any error messages related to import process.
- Add specific button to close window only when USER chooses to close the selection window.

**Comment by igorlogius** [comment]
Hi, thanks for reporting this issue.

I tried to reproduce it with firefox 132.0.2 (current stable) and the import function for json and html still seems to work as far as i can tell. 

To get a bit more information, please do the following on your setup

1. open `about:debugging`
2. click on `This Firefox`
3. click the `Inspect` next to the listed `Bookmark Branch Porter` entries 
4. Switch to the `Console` tab in the little window that opens
5. Leave that window open and try to import something again with BBP

If we are lucky after the import failed, we get some error output in the `Console` view/tab. 

Regarding your recommendations. I can see how improving the error handing for this addons would benefit the user i just dont want to manually start analysing and parsing json/html, so i'll have to think about what to do and expose a bit.

**Comment by igorlogius** [comment]
Added some info/error output to version `1.4.19`

After an attempted import the page will stay open and display either 

![2024-11-17_16-48](https://github.com/user-attachments/assets/3163928e-f6b7-4ea4-a1d9-a80bd1447b38)

or a error message

![2024-11-17_16-49](https://github.com/user-attachments/assets/27af47b6-1cac-46fe-a654-3c5727088c8c)
