### ISSUE TITLE
Open in Temp Container: container name shortening

### ISSUE THREAD

**Issue by privacy-advo** [igorlogius/igorlogius#63]
### Describe your suggestion

I suggest to shorten the temporary container's name/digits.
Why? Everything beyond "Temp 12345678" won't be displayed. It's impossible to know if you're in separate containers if, and this happens regularly as there aren't many colours, both tabs have the same colour but you can't read the last digits.

**Comment by igorlogius** [comment]
Hi, thanks for bringing this to my attention.

I could easily revers the timestamp ... that should lower the probability of creating duplicate IDs. 

Sounds good?

**Comment by privacy-advo** [comment]
Thanks for the fast response (as always!). The quick fix works for me.
Word combinations could be visually easier. But I think the initial problem would be the same with word combinations as the obstacle is the limited display in the URL bar.

**Comment by igorlogius** [comment]
If its good enough for you, than thats ok. 

Another options would have been to use character symbols as part of the container name (aka. emojis)

**Comment by privacy-advo** [comment]
Thanks for the great addon. It is the only thing preventing me to leave Firefox for Brave for its "Forget me" feature. If I would loose OITC I probably would leave FF - which I don't because uBo only blossoms on FF.

**Comment by privacy-advo** [comment]
Now it's clear at a glance. Perfect.
