### ISSUE TITLE
Load Background Tabs On Select: Firefox opens an empty tab in auxclick event

### ISSUE THREAD

**Issue by eight04** [igorlogius/igorlogius#64]
### Can you reproduce your issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

yes - Please only select if you actually did!

### Steps to Reproduce

1. Install and enable the addon.
2. Go to https://codepen.io/eight04/pen/dPbydNg
3. Middle-click "FOO"

### Expected Result

Open a background tab whose URL is example.com.

### Actual Result

Open an empty background tab.

Live example: https://forum.gamer.com.tw/B.php?bsn=74934
![圖片](https://github.com/user-attachments/assets/69ddc79e-331c-470b-b5fa-f9b4bc022e62)

**Comment by eight04** [comment]
Firefox Nightly 135.0a1

**Comment by igorlogius** [comment]
Thanks for reporting this issue!
I'll take a look and see if there is something i can do.

**Comment by igorlogius** [comment]
Seems to be a timing issue, the tab is initally created as a 'about:blank' tab and a few ms later gets updated and assigned the correct URL. 

LBToS seems to be to fast and discards the tab before it gets assigned its expected URL.

Not sure if this is a BUG or not ... i would kind of have expected that it is still doable to assign a discarded tab a new URL without it loading that url immediately, but that doenst seem to be the case at the moment. 

As a workaround i'll add a little delay (1-2s) before discarding happens which should in most cases (assuming the URL update isnt blocked by something else) be enough to make this behave as expected.

**Comment by igorlogius** [comment]
version `1.2.9` should fix the issue.

[demo-2024-11-27_13.24.13.webm](https://github.com/user-attachments/assets/1e30f3dc-49b9-4f26-ac0b-8006287f8543)

**Comment by eight04** [comment]
Does it relate to this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1620774

**Comment by igorlogius** [comment]
> Does it relate to this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1620774

Not as far as i can see with LBToS at least i dont use the webNavigation, but the tabs.onUpdated callback to monitor for url changes and check if a tab is created in the background.

I'd assume the some would be doable with the webNavigation api, but i am not sure what drawback or improvement one would have over the other, so for now i think i'll stick with what i have unless ... some issue pops up that i can not find a suitable solution for ... then i might ... look around a bit more.
