### ISSUE TITLE
List Feeds AMO update issue

### ISSUE THREAD

**Issue by atomGit** [igorlogius/igorlogius#65]
### What's on your mind?

i see that a new build of List Feeds was uploaded to AMO, but when i check for extension updates in firefox, it's not detected

wondering if this is because of versioning?

AMO version 1.1.0
installed version 1.17.43

**Comment by atomGit** [comment]
i removed 1.17.43 and installed 1.1.0 - there are no rules with the latter version and the import function doesn't work (i'm re-installing the old version for now)

**Comment by atomGit** [comment]
i was accessing the rules from about:addons > List Feeds > Preferences and the list was empty

also when i removed 1.1.0 and installed the other version, again the list was empty, but i was able to import

**Comment by igorlogius** [comment]
So, i found the bug ... i forgot to remove a port on the options page, which caused the issue with rendering. 

version 1.1.2 should fix the issue. 

Sorry for your troubles.

**Comment by atomGit** [comment]
no problem! i'm glad to be able to use your extension - it is a valuable one for me

and yes, 1.1.2 solved the issue
