### ISSUE TITLE
load-background-tabs-on-select: Toggle state isn't persisted

### ISSUE THREAD

**Issue by brian6932** [igorlogius/igorlogius#67]
### Can you reproduce your issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

yes - Please only select if you actually did!

### Steps to Reproduce

1. Toggle off
1. Close browser
1. Open browser
1. It's now on

### Expected Result

Should be off, whether this is a feature request or a bug is arguable.

### Actual Result

Starting the browser will always set it's state to on.

**Comment by igorlogius** [comment]
Yeah, changing the switch to be persistent between might be a more expected behaviour. 
In the past i was of a differenet opinion but now it seems to make more sense. 

I'll see what i can do.

**Comment by igorlogius** [comment]
Should now work as expected for `1.2.10`

**Comment by brian6932** [comment]
Ok, this is not quite fixed in `1.2.10` for me, it takes like a second after launching the browser, but it turns on again.

**Comment by igorlogius** [comment]
You mean that the toolbar icon is not showing "ON" immediately? 
I am not sure if i can do anything about that, but i'll see what i can do.

**Comment by brian6932** [comment]
> You mean that the toolbar icon is not showing "ON" immediately?

Nah, I mean, despite being in an `OFF` state, it displays as `ON` when launched.

**Comment by igorlogius** [comment]
My bad, i forget to remove something.
Hope this is better.

**Comment by brian6932** [comment]
Fixed.
