### ISSUE TITLE
Load Background Tabs on Select

### ISSUE THREAD

**Issue by srjjgm** [igorlogius/igorlogius#69]
### Can you reproduce your issue in a 2nd new unmodified firefox profile with only the addon installed in its latest version  on the current stable firefox

yes - Please only select if you actually did!

### Expected Result

Version 1.2.11 does not work (Firefox 133 and 134 beta).
Version 1.2.9 works normally.

**Comment by igorlogius** [comment]
Hi. In a recent update the operation state (ON/OFF) which can be toggled via the toolbar button has been made persistent (between restarts). 

Please try enabeling the addon via the toolbar button and let me know if that was the issue or not.

**Comment by srjjgm** [comment]
Yes, that was the problem. I don't usually use the toolbar button, so I didn't see this change.
Thank you very much for keeping this wonderful extension working.
