### ISSUE TITLE
Toolbar Countdown revival?

### ISSUE THREAD

**Issue by Vingolf** [igorlogius/igorlogius#7]
Hi igorlogius,

I am still using your Toolbar Countdown addon (v.1.1.8) 😎.

It is nice 😀.

Is there a chance for a revival of this addon 😉

Regards, 
Vingolf

**Comment by igorlogius** [comment]
i dont think there is enough demand for this addon to warrent me putting it back on AMO.

But i am still hosting it in my [not-on-amo repo](https://github.com/igorlogius/not-on-amo/) repo, so feel free to report bugs or suggestions there, just dont expect any activ development outside of user request.

**Comment by Vingolf** [comment]
> But i am still hosting it in my [not-on-amo repo](https://github.com/igorlogius/not-on-amo/) repo, so feel free to report bugs or suggestions there

Thank you 😀

I have opened an issue [Countdown does not start · Issue #8](https://github.com/igorlogius/not-on-amo/issues/8)
