### ISSUE TITLE
mute-unfocused-tabs: Right click disable/enable manual mode.

### ISSUE THREAD

**Issue by derekschrock** [igorlogius/igorlogius#71]
### Describe your suggestion

When using this add-on I mainly use it on certain days I have multiple tabs with audio however for all other use cases I would rather have audio not muted and not have to toggle mute/unmute. 

Would it be possible to globally disable/enable muting (Manual mode) without navigating the Firefox setting (hamburger button or right click manage settings, options, manual mode)?  Possible right click action (ex: ublock has a Block element in right click) alt, control, or shift click to control this.

**Comment by igorlogius** [comment]
Hi. Thanks for making a suggestion. 

Would you be fine with shortcuts you can set to toggle the modes instead of a context menu entry? Some users are rather sensitive about addons adding context menus so i am trying to only add them when necessary.

**Comment by derekschrock** [comment]
The keyboard  shortcut might be fine however juszt to be clear this isn't the main right click menu this request would only apply to the right click context menu when you right click the mute unfocused tabs icon in the menu bar.  I think that's a less sensitive place for the item.

**Comment by igorlogius** [comment]
Ah guess i misunderstood. Adding something to the context menu of the toolbar button is obviously fine and btw. easier than adding shortcuts.

I'll see what i can do.

**Comment by igorlogius** [comment]
`1.4.16`

![image](https://github.com/user-attachments/assets/78d9574f-decc-4295-ba84-420b68b840b0)

**Comment by derekschrock** [comment]
Looks good.  Thanks.
