### ISSUE TITLE
mute-unfocused-tabs: Option to follow browser/system theme mode

### ISSUE THREAD

**Issue by derekschrock** [igorlogius/igorlogius#72]
### Describe your suggestion

When selecting Options tab from from Managed Extension the Options page does not follow the browser theme (Auto, White, Dark) setting and is always white.  Can this tab follow the browser setting?    For an extension that follows this setting you can look at "YouTube Auto HD + FPS".

**Comment by igorlogius** [comment]
Hi. Thanks for making this suggestion. 

yeah i am a bit lazy with the whole theme switching stuff, if it's all the same to you i'll just make the background gray, that should fit reasonably well with either theme.

**Comment by igorlogius** [comment]
`1.4.14` not great but better than having to fidde around with CSS classes ;) 


| | |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/cb29192f-82be-48d6-8dc2-ec1447b89ade) | ![image](https://github.com/user-attachments/assets/190aa561-ef94-413f-9fd1-150da0e1949a) |

**Comment by derekschrock** [comment]
This was better but still a little bright.  However, if you look at pull request https://github.com/igorlogius/mute-unfocused-tabs/pull/8 I believe this will follow browser and system (tested with Window 11 and Firefox flip flopping light/dark at the system and browser theme).
